### ISSUE TITLE
Directory Iteration

### ISSUE THREAD

**Issue by Offroaders123** [BenjaminAster/TypeScript-types-for-new-JavaScript#1]
I tried iterating over a `FileSystemDirectoryHandle` using the async-iterator syntax, but it doesn't appear to be present on the type definitions for that. This causes a type error in my editor.

I looked at the type definitions for it using "Go to Type Definition", and it looks like it's not your library that defines `FileSystemFileHandle` or `FileSystemDirectoryHandle` anymore, but rather the standard TypeScript library.

Any ideas where I can also make an issue for this, so the standard library can be configured correctly too? [Here's the part of the spec](https://fs.spec.whatwg.org/#api-filesystemdirectoryhandle-asynciterable) that I was trying to use in my code, and it was the `FileSystemDirectoryHandle.values()` call that doesn't appear to be defined.

Here's a TypeScript version of the code with the error that I ran into:
```ts
// Sorry this code is a bit of a mess, I ran into this issue while doing some refactoring, haha

export interface ReadDirOptions {
  recursive?: boolean;
}

export async function readdir(directoryHandle: FileSystemDirectoryHandle, { recursive = false }: ReadDirOptions = {}): Promise<FileSystemHandle[]> {
  const handles: FileSystemHandle[] = [];

  for await (const handle of directoryHandle.values()){
    // Property 'values' does not exist on type 'FileSystemDirectoryHandle'. ts(2339)

    handles.push(handle.kind === "directory" && recursive === true ? await readdir(handle,{ recursive }) : handle);
  }

  return recursive === true ? handles.flat(Infinity) : handles;
}
```

**Comment by BenjaminAster** [comment]
Microsoft uses their own tool ([microsoft/TypeScript-DOM-lib-generator](https://github.com/microsoft/TypeScript-DOM-lib-generator)) to automatically generate TypeScript's [`lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts) file. You'd have to open an issue there for them to change _the generating code_ itself to recognize WebIDL's async iterator syntax; just manually changing `lib.dom.d.ts` won't help. In my experience Microsoft is extremely slow with fixing stuff of this "low" priority.

So in the meantime, I've now manually added the async iterator myself to [`file-system.d.ts`](https://github.com/BenjaminAster/TypeScript-types-for-new-JavaScript/blob/main/whatwg/file-system.d.ts); simply update to `new-javscript@0.1.10` and it should work.

**Comment by Offroaders123** [comment]
Great! Thanks for the info, and for the fix too. [Here's the project](https://github.com/Offroaders123/Librar.io/blob/f0abd731a82fb85cc13576b26471a8fb0791ca44/src/fsa.js) where I'm using this in. I will update `new-javascript` in the morning!
