### ISSUE TITLE
Cannot install via Yarn

### ISSUE THREAD

**Issue by Nantris** [BenjaminAster/TypeScript-types-for-new-JavaScript#3]
Thanks for your great work on this; I'm excited to give it a try! Unfortunately when I try to install it via `yarn` I get:

> error An unexpected error occurred: "https://registry.yarnpkg.com/new-javscript: Not found".

I thought Yarn just reflected the npm registry. Is there something else that would need to be done for this to be installable via Yarn?

**Comment by Nantris** [comment]
Whoops; I swear I can spell! Thank you again.

**Comment by BenjaminAster** [comment]
Wait... I think this was my fault! I just noticed that in the "install via npm" code block in the Readme **_I_** misspelled "new-javascript" as "new-javscript"... Should be fixed now, and thanks for making me notice it! I guess that has been lurking around in the Readme for months (or years) 😬. Oh, and thanks for giving the project a try btw!
